# COGS 108 - Data Checkpoint

# Names

- Nilou Shahbandi
- Leonardo Gonzalez
- Brian Chen
- Tin-Trung Pham
- Zhongkang(ken) Fang

<a id='research_question'></a>
# Research Question

*How do different pollutants in California impact the rate of cancer in individuals, and how does pollutants affect rate of Asthma?*

# Dataset(s)

*Fill in your dataset information here*

(Copy this information for each dataset)
- Dataset Name: Current Asthma by State, 2018
- Link to the dataset: https://www.lung.org/research/trends-in-lung-disease/asthma-trends-brief/data-tables/asthma-current-state
- Number of observations: 32

 National child asthma prevalence is based on data from 31 states and Washington, D.C. 
 Child asthma data is from 2018 unless an earlier year is noted, in which case that is the most recent year of data available.  If a state has not collected child asthma data since 2011, no rate is listed.
 
 

If you plan to use multiple datasets, add 1-2 sentences about how you plan to combine these datasets.
- This dataset is by state, maybe we can combine with the AQI by state to do a comparison with Asthmas by state vs Pollution by state

# Setup

In [8]:
## YOUR CODE HERE
import pandas as pd 
import numpy as ny 
# Ashthma by states: https://www.lung.org/research/trends-in-lung-disease/asthma-trends-brief/data-tables/asthma-current-state
df = pd.read_csv('data/Asthma.csv')
df.head()

        State ChildCount Percent    Year AdultCount Percent.1
0     Alabama    141,500  13.20%  2014.0    394,600    10.50%
1      Alaska        ---     ---     NaN     50,700     9.20%
2     Arizona    129,200   8.10%  2016.0    545,100    10.00%
3    Arkansas        ---     ---     NaN    225,900     9.80%
4  California    542,700   6.20%     NaN  2,607,600     8.50%

*Fill in your dataset information here*

(Copy this information for each dataset)
- Dataset Name: annual_aqi_by_county_2010
- Link to the dataset:https://aqs.epa.gov/aqsweb/airdata/download_files.html
- Number of observations: 999

### Description:
- data contains AQI, calculated each day for each monitor for the Criteria Gases and PM10 and PM2.5 (FRM and non FRM).
- of Days CO, NO2, Ozone, SO2, PM2.5, PM10 where the daily monitor criteria were met.


### If you plan to use multiple datasets, add 1-2 sentences about how you plan to combine these datasets.
- Since the data comes by counties within states we can extract the counties for all california and merge with our county_cancer data.
- We can also take the mean of all counties for each state and combine with the asthma data by states.

In [48]:
aqi = pd.read_csv('data/annual_aqi_by_county_2010.csv')
#aqi.columns = aqi.columns.str.replace(' ', '')
aqi.columns = aqi.columns.str.lower()
aqi.head()

,state,county,year,days with aqi,good days,moderate days,unhealthy for sensitive groups days,unhealthy days,very unhealthy days,hazardous days,max aqi,90th percentile aqi,median aqi,days co,days no2,days ozone,days so2,days pm2.5,days pm10
0,Alabama,Baldwin,2010,274,188,80,6,0,0,0,150,71,43,0,0,192,0,82,0
1,Alabama,Clay,2010,113,79,34,0,0,0,0,86,60,42,0,0,0,0,113,0
2,Alabama,Colbert,2010,355,208,146,1,0,0,0,105,67,47,0,0,114,0,241,0
3,Alabama,DeKalb,2010,358,248,106,4,0,0,0,101,74,43,0,0,303,0,55,0
4,Alabama,Elmore,2010,241,181,55,5,0,0,0,112,71,43,0,0,241,0,0,0

*Fill in your dataset information here*

(Copy this information for each dataset)

- Dataset Name: Lung and Bronchus Cancer Incidence in California
- Link to the dataset: [California Cancer Registry](https://explorer.ccrcal.org/application.html?site=47&data_type=1&graph_type=13&compareBy=sex&chk_sex_1=1&race=1&age_range=9&hdn_stage=101&year=4&advopt_precision=4&advopt_display=2#tableWrap)
- Number of observations: 9306

This data shows us the counts of lung or bronchus cancer in individuals of all races and sexes by county in California. It also includes breakdowns by age with additional statistics regarding the data.

We plan to use this data in combination with the pollution data to track the impact of pollution on lung or bronchus cancer indcidents in individuals living in California. By comparing changes in pollution with changes in cancer incident counts.

In [85]:
county_cancer = pd.read_csv('data/countyCancer.csv')
county_cancer.head()

,Year,Sex,Race/Ethnicity,Age,California Region,Stage at Diagnosis,"Age-adjusted Rate per 100,000",Age-adjusted Rate Standard Error,Age-adjusted Rate Lower Confidence Interval,Age-adjusted Rate Upper Confidence Interval,Count
0,2010,Both Sexes,All Races,All Ages,Alameda County,All Stages,44.8118,1.8013,41.3504,48.4812,646
1,2010,Both Sexes,All Races,All Ages,Butte County,All Stages,63.0616,4.9021,53.8195,73.5358,171
2,2010,Both Sexes,All Races,All Ages,Contra Costa County,All Stages,50.2429,2.2114,46.0016,54.7691,536
3,2010,Both Sexes,All Races,All Ages,El Dorado County,All Stages,54.2364,4.9899,44.8983,65.1021,124
4,2010,Both Sexes,All Races,All Ages,Fresno County,All Stages,51.7782,2.6266,46.7576,57.1687,401

# Data Cleaning

Describe your data cleaning steps here.

In [50]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

In [105]:
# Data cleaning for AQI by states
aqi_state = aqi.groupby(['state']).agg('mean')
#states.shape
aqi_state.drop(['good days', 'moderate days', 'very unhealthy days', 'unhealthy days',
                'hazardous days', 'unhealthy for sensitive groups days'],
               inplace = True, axis=1)

aqi_state["year"] = aqi_state["year"].astype(int)
aqi_state.head()

,year,days with aqi,max aqi,90th percentile aqi,median aqi,days co,days no2,days ozone,days so2,days pm2.5,days pm10
state,,,,,,,,,,,
Alabama,2010,282.263158,112.263158,70.315789,46.157895,0.052632,0.000000,131.000000,0.210526,142.105263,8.894737
Alaska,2010,262.125000,88.500000,44.875000,19.750000,2.375000,0.000000,59.375000,0.000000,191.000000,9.375000
Arizona,2010,309.769231,238.384615,75.000000,46.000000,0.000000,5.615385,180.384615,22.000000,22.461538,79.307692
Arkansas,2010,222.647059,100.000000,63.529412,41.352941,0.000000,2.941176,110.352941,14.470588,94.882353,0.000000
California,2010,350.396226,305.603774,80.603774,45.301887,0.150943,8.886792,222.509434,0.056604,105.943396,12.849057

In [106]:
aqi.head()
aqi_ca = aqi[aqi['state'] == 'California']
aqi_ca = aqi_ca.reset_index(drop=True)
aqi_ca.drop(['good days', 'moderate days', 'very unhealthy days', 'unhealthy days',
                'hazardous days', 'unhealthy for sensitive groups days'],
               inplace = True, axis=1)
#aqi_ca['county'] = aqi_ca['county'].apply(standardize_region)

#aqi_ca.shape
county_cancer_2010 = county_cancer[county_cancer['Year'] == 2010]
county_cancer_2010 = county_cancer_2010[county_cancer_2010['Age'] == 'All Ages']
county_cancer_2010['California Region'] = county_cancer_2010['California Region'].apply(standardize_region)
county_cancer_2010

UnboundLocalError: local variable 'output' referenced before assignment

In [95]:
# remove " county"
def standardize_region(str_in):
    
    try:
        str_in = str_in.lower()
        str_in = str_in.strip()

        if 'county' in str_in:
            str_in = str_in.replace('county', '')
            output = str_in
    except:
        output = np.nan
        
    return output

In [102]:
aqi_ca

,state,county,year,days with aqi,max aqi,90th percentile aqi,median aqi,days co,days no2,days ozone,days so2,days pm2.5,days pm10
0,California,Alameda,2010,365,179,68,43,0,30,137,0,198,0
1,California,Amador,2010,361,151,64,35,0,0,361,0,0,0
2,California,Butte,2010,365,126,84,47,0,0,264,0,101,0
3,California,Calaveras,2010,365,154,84,41,0,0,311,0,54,0
4,California,Colusa,2010,353,119,49,38,0,0,306,0,42,5
5,California,Contra Costa,2010,365,154,64,39,0,11,287,2,63,2
6,California,Del Norte,2010,110,52,26,12,0,0,0,0,65,45
7,California,El Dorado,2010,365,192,93,42,0,0,365,0,0,0
8,California,Fresno,2010,365,209,130,70,0,1,211,0,153,0
9,California,Glenn,2010,365,91,58,42,0,0,250,0,114,1
10,California,Humboldt,2010,365,71,39,29,5,6,316,0,35,3
11,California,Imperial,2010,365,140,108,53,1,53,265,0,42,4
12,California,Inyo,2010,365,4466,93,44,0,0,259,0,31,75
13,California,Kern,2010,365,202,151,79,0,1,220,0,140,4
14,California,Kings,2010,365,208,129,70,0,1,151,0,211,2
15,California,Lake,2010,361,74,44,35,0,0,360,0,1,0
16,California,Los Angeles,2010,365,200,138,76,0,39,170,0,155,1
17,California,Madera,2010,364,201,90,46,0,21,268,0,73,2
18,California,Marin,2010,365,128,58,38,0,18,103,0,244,0
19,California,Mariposa,2010,365,187,93,49,0,0,311,0,52,2
20,California,Mendocino,2010,361,72,52,34,0,0,83,0,225,53
21,California,Merced,2010,365,177,101,55,0,3,194,0,165,3
22,California,Mono,2010,365,4240,61,18,0,0,0,0,12,353
23,California,Monterey,2010,365,100,48,36,0,3,269,0,91,2
24,California,Napa,2010,365,159,60,39,0,3,184,0,178,0
25,California,Nevada,2010,365,154,90,44,0,1,346,0,18,0
26,California,Orange,2010,365,177,80,56,0,22,100,0,243,0
27,California,Placer,2010,365,200,97,50,0,6,229,0,130,0
28,California,Plumas,2010,124,110,75,33,0,0,0,0,124,0
29,California,Riverside,2010,365,217,156,87,0,6,193,0,135,31
30,California,Sacramento,2010,365,207,97,49,0,14,228,0,122,1
31,California,San Benito,2010,365,126,58,40,0,0,332,0,33,0
32,California,San Bernardino,2010,365,219,164,81,0,10,229,1,125,0
33,California,San Diego,2010,365,181,93,61,0,42,172,0,148,3
34,California,San Francisco,2010,365,125,67,40,0,51,96,0,217,1
35,California,San Joaquin,2010,365,174,81,45,0,20,196,0,149,0
36,California,San Luis Obispo,2010,365,161,97,51,0,0,258,0,66,41
37,California,San Mateo,2010,362,122,56,35,2,23,165,0,172,0
38,California,Santa Barbara,2010,365,143,65,44,0,1,299,0,64,1
39,California,Santa Clara,2010,365,164,66,42,0,20,172,0,173,0
40,California,Santa Cruz,2010,365,95,44,34,0,0,241,0,124,0
41,California,Shasta,2010,365,119,84,43,0,0,354,0,11,0
42,California,Siskiyou,2010,361,90,44,33,0,0,352,0,8,1
43,California,Solano,2010,365,136,64,39,0,21,225,0,119,0
44,California,Sonoma,2010,365,93,53,32,0,8,182,0,174,1
45,California,Stanislaus,2010,365,177,102,53,0,0,216,0,149,0
46,California,Sutter,2010,365,170,69,44,0,15,168,0,182,0
47,California,Tehama,2010,365,136,90,50,0,0,214,0,150,1
48,California,Trinity,2010,122,35,21,10,0,0,0,0,84,38
49,California,Tulare,2010,365,197,150,69,0,1,219,0,144,1
50,California,Tuolumne,2010,365,147,80,41,0,0,365,0,0,0
51,California,Ventura,2010,365,161,87,47,0,11,322,0,32,0
52,California,Yolo,2010,362,109,57,38,0,9,275,0,74,4